export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const CREATE_GAME_SUCCESS  = "CREATE_GAME_SUCCESS";
export const DELETE_GAMES_SUCCESS = "DELETE_GAMES_SUCCESS";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
export const ADD_OWNER_SUCCESS = "ADD_OWNER_SUCCESS";
export const REMOVE_OWNER_SUCCESS = "REMOVE_OWNER_SUCCESS";
